name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: docker compose up -d
        working-directory: examples/smarthome-api
      - run: ./scripts/apply-schema.sh
        working-directory: examples/smarthome-api
      - run: docker compose ps
        working-directory: examples/smarthome-api
